---

- name: Installing basice dependenceis in ubuntu
  hosts: "{{ host_name }}"
  user: "{{ user_name }}"
  sudo: true

  vars_files:
    - "../vars/main.yml"

  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

  gather_facts: false

  tasks:
      - name: 1. Set MySQL root password before installing
        debconf: name='mysql-server' question='mysql-server/root_password' value={{ mysql_password }} vtype="password"

      - name: 2. Confirm MySQL root password before installing
        debconf: name='mysql-server' question='mysql-server/root_password_again' value={{ mysql_password }} vtype='password'

      - name: 3. Installing dependencies
        apt: name="{{ item }}" state=installed force=yes update_cache=yes cache_valid_time=3600
        with_items: "{{ python_dependencies + build_dependencies}}"

      - name: 4. Deleting anonymous MySQL server user for localhost
        mysql_user: user="" state=absent login_password={{ mysql_password }} login_user=root

      - name: 5. Securing the MySQL root user
        mysql_user: user="" password={{ mysql_password }} host='{{ item }}' login_password={{ mysql_password }} login_user=root
        with_items:
          - 127.0.0.1
          - localhost
          - ::1

      - name: 6. Removing the MySQL test database
        mysql_db: db=test state=absent login_password={{ mysql_password }} login_user=root

      - name: 8. Creating Code and Installs folder
        file: path=/home/{{ user_name }}/{{ item }} state=directory
        with_items:
          - Code
          - Installs

      - name: Does the Google apt file exist?
        command: test -f {{chrome_apt_file}}
        register: google_apt_exists
        ignore_errors: True

      - name: Add Google Chrome key
        shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
        when: google_apt_exists.rc == 1

      - name: Add Google Chrome repo
        copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest={{chrome_apt_file}} owner=root group=root mode=644
        when: google_apt_exists.rc == 1

      - name: Update apt cache
        apt: update_cache=yes
        when: google_apt_exists.rc == 1

      - name: Install Google Chrome
        apt: pkg=google-chrome-stable state=installed

      - name: Add sublime key
        shell: wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -

      - name: Add sublime repo
        copy: content="deb https://download.sublimetext.com/ apt/stable/" dest={{sublime_apt_file}} owner=root group=root mode=644

      - name: Does the Sublime apt file exist?
        command: test -f {{sublime_apt_file}}
        register: sublime_apt_exists
        ignore_errors: True

      - name: Update apt cache
        apt: update_cache=yes
        when: sublime_apt_exists.rc == 1

      - name: Update apt cache
        apt: update_cache=yes
        when: google_apt_exists.rc == 1

      - name: Install Sublime Chrome
        apt: pkg=sublime-text state=installed

      - name: Add VS Code Keys
        apt_key:
          url: "https://packages.microsoft.com/keys/microsoft.asc"
          state: present

      - name: Add VS Code Repo
        apt_repository:
          repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
          filename: vscode
          state: present
          update_cache: yes

      - name: Install VS Code
        apt:
          name: code
          update_cache: true
